FROM python:3.9-slim

WORKDIR /app

# Instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código
COPY . .

# Inicializamos la DB antes de arrancar (importante para que el login funcione)
RUN python create_db.py

EXPOSE 5000

CMD ["python", "vulnerable_flask_app.py"]